#!/usr/bin/env bash
# gen_code_map.sh — M7: generate CODE_MAP.md instead of hand-maintaining it.
#
# The hand-written version had drifted in exactly the way a hand-written inventory does: it listed a
# `_tools/` section for scripts that live *outside* the repository, and its line counts were from the
# session that wrote it. An inventory that is regenerated cannot drift; an inventory that is typed by
# hand always does.
#
# How it works, and why it is split this way: everything **above** the `<!-- CODE_MAP:GENERATED -->`
# marker is human narrative and is never touched. Everything below it is computed from the tree and the
# registry, so a regeneration is a no-op on a clean checkout and a diff only when something real
# changed. That is the property that makes the file trustworthy.
#
# Usage: bash scripts/gen_code_map.sh [--check]
#   (no flag)  rewrite the generated section in place
#   --check    fail if the file on disk differs from what would be generated (CI / pre-push)
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

TARGET="CODE_MAP.md"
MARKER="<!-- CODE_MAP:GENERATED -->"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# Fork-only paths, in the order a reader wants them: the watch, then the phone feature set, then the
# infrastructure. A path is "fork-only" when it does not exist in the upstream ref — that is the same
# question the touchpoint guard asks, so the two cannot disagree.
UPSTREAM_REF="${UPSTREAM_REF:-upstream/master}"
if ! git rev-parse --verify --quiet "$UPSTREAM_REF" >/dev/null; then
    UPSTREAM_REF="$(git merge-base HEAD "$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null || echo HEAD)" 2>/dev/null || echo HEAD)"
fi

owned_by_upstream() {
    git cat-file -e "$UPSTREAM_REF:$1" 2>/dev/null
}

line_count() { wc -l < "$1" | tr -d ' '; }

emit_inventory() {
    local title="$1"; shift
    printf '### %s\n\n' "$title"
    printf '| File | Lines | Status |\n|---|---|---|\n'
    for path in "$@"; do
        [ -f "$path" ] || continue
        local status="fork-only"
        owned_by_upstream "$path" && status="upstream (budgeted)"
        printf '| `%s` | %s | %s |\n' "$path" "$(line_count "$path")" "$status"
    done
    printf '\n'
}

emit_generated() {
    printf '%s\n' "$MARKER"
    printf '<!-- Generated by scripts/gen_code_map.sh. Do not hand-edit below this line: -->\n'
    printf '<!-- run the script instead, and put prose above the marker. -->\n\n'
    printf 'Upstream ref used for the classification: `%s`\n\n' "$UPSTREAM_REF"

    # ── fork-only: the watch ────────────────────────────────────────────────────────────────
    mapfile -t wear_main < <(find wear/src/main -name '*.kt' | sort)
    mapfile -t wear_test < <(find wear/src/test -name '*.kt' | sort)
    mapfile -t wear_android < <(find wear/src/androidTest -name '*.kt' 2>/dev/null | sort)
    emit_inventory "wear/ — main" "${wear_main[@]}"
    emit_inventory "wear/ — unit tests" "${wear_test[@]}"
    if [ "${#wear_android[@]}" -gt 0 ]; then
        emit_inventory "wear/ — instrumented tests" "${wear_android[@]}"
    else
        printf '### wear/ — instrumented tests\n\n_none: `wear/src/androidTest` does not exist._\n\n'
    fi

    # ── fork-only: the phone feature set ────────────────────────────────────────────────────
    mapfile -t ap_main < <(find app/src/main/java/com/newoether/agora/autopilot -name '*.kt' | sort)
    mapfile -t ap_test < <(find app/src/test/java/com/newoether/agora/autopilot -name '*.kt' | sort)
    mapfile -t ap_android < <(find app/src/androidTest/java/com/newoether/agora/autopilot -name '*.kt' 2>/dev/null | sort)
    emit_inventory "app/.../autopilot/ — main" "${ap_main[@]}"
    emit_inventory "app/.../autopilot/ — unit tests" "${ap_test[@]}"
    [ "${#ap_android[@]}" -gt 0 ] && emit_inventory "app/.../autopilot/ — instrumented tests" "${ap_android[@]}"

    # ── the scripts ────────────────────────────────────────────────────────────────────────
    mapfile -t scripts < <(find scripts -type f | sort)
    emit_inventory "scripts/" "${scripts[@]}"

    # ── upstream files this fork edits, straight from the registry ─────────────────────────
    printf '### Upstream files this fork edits\n\n'
    printf 'Parsed from `UPSTREAM_TOUCHPOINTS.md`'"'"'s `GUARD:DATA` block — the same data the guard reads,\n'
    printf 'so this table cannot disagree with what the guard enforces.\n\n'
    printf '| Path | Budget (changed lines) | Current |\n|---|---|---|\n'
    while read -r line; do
        case "$line" in \#*|'') continue ;; esac
        local path max current
        path="$(printf '%s' "${line%%::*}" | tr -d '[:space:]')"
        max="$(printf '%s' "${line##*max=}" | tr -d '[:space:]')"
        [ -n "$path" ] || continue
        current="$(git diff --numstat "$(git merge-base "$UPSTREAM_REF" HEAD 2>/dev/null || echo "$UPSTREAM_REF")" -- "$path" 2>/dev/null |
            awk '{print $1 + $2}')"
        printf '| `%s` | %s | %s |\n' "$path" "$max" "${current:-0}"
    done < <(awk '/GUARD:DATA:START/{f=1;next} /GUARD:DATA:END/{f=0} f' UPSTREAM_TOUCHPOINTS.md)
    printf '\n'

    # HERMES INTEGRATION POINT: this line used to print `$(git rev-parse --short HEAD)`, i.e. the hash
    # of the commit that was *being made*. The file therefore could never be up to date: committing the
    # regenerated CODE_MAP.md moved HEAD, so the next `--check` compared the new hash against the one
    # written a moment earlier and failed. A check that cannot pass on a clean tree is not a check.
    # The upstream ref is stable and is the thing the table is actually keyed to.
    printf 'Generated from `%s` (line counts are `git diff --numstat` against that ref).\n' "$UPSTREAM_REF"
}

if [ "$CHECK" -eq 1 ]; then
    TMP="$(mktemp)"
    { awk -v m="$MARKER" 'BEGIN{done=0} { if (done==0 && index($0,m)==1) { exit } print }' "$TARGET"
      emit_generated; } > "$TMP"
    # HERMES INTEGRATION POINT: `diff` compares bytes, and this repository checks out with CRLF line
    # endings on Windows while the generator emits LF — so on a fresh clone (which is what CI has)
    # every single line differed and `--check` reported the whole file as stale. Proved: on a shallow
    # clone of the pushed commit, `diff` printed `1,193c1,193` and exited 1 while the *content* was
    # identical. Normalising line endings before the comparison is the fix; `tr -d '\r'` is POSIX and
    # costs nothing.
    if diff -q <(tr -d '\r' < "$TARGET") <(tr -d '\r' < "$TMP") >/dev/null; then
        printf 'gen_code_map: CODE_MAP.md is up to date.\n'
        rm -f "$TMP"
        exit 0
    fi
    printf 'gen_code_map: FAIL CODE_MAP.md is stale — run bash scripts/gen_code_map.sh\n'
    diff "$TARGET" "$TMP" | head -20
    rm -f "$TMP"
    exit 1
fi

TMP="$(mktemp)"
{ awk -v m="$MARKER" 'BEGIN{done=0} { if (done==0 && index($0,m)==1) { exit } print }' "$TARGET"
  emit_generated; } > "$TMP"
mv "$TMP" "$TARGET"
printf 'gen_code_map: wrote %s (%s lines).\n' "$TARGET" "$(wc -l < "$TARGET" | tr -d ' ')"
